import { useEffect, useState } from 'react';
function today(){return new Date().toISOString().slice(0,10)}
function fmt(d:string){return new Date(d).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});}

export default function StaffPanel(){
 const [from,setFrom]=useState(today()); const [to,setTo]=useState(today()); const [bookings,setBookings]=useState<any[]>([]); const [summary,setSummary]=useState<any[]>([]); const [staff,setStaff]=useState<any>(null);
 async function load(){const q=`from=${from}&to=${to}`; let r=await fetch('/api/staff/bookings?'+q); if(r.status===401){location.href='/staff/login';return;} let d=await r.json(); setBookings(d.bookings); setStaff(d.staff); r=await fetch('/api/staff/summary?'+q); setSummary(await r.json());}
 useEffect(()=>{load();},[from,to]);
 const mine=bookings.filter(b=>b.staffId===staff?.id); const others=bookings.filter(b=>b.staffId!==staff?.id);
 return <main className="min-h-screen bg-[#f8eee8] px-4 py-8"><section className="mx-auto max-w-7xl"><h1 className="text-3xl font-bold text-[#8a5a42]">Agenda de {staff?.name}</h1><div className="mt-4 flex gap-3"><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-xl border p-3"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded-xl border p-3"/></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><div><h2 className="mb-3 text-xl font-semibold text-[#8a5a42]">Mis citas</h2>{mine.map(b=><div key={b.id} className="mb-3 rounded-2xl bg-white p-4 shadow"><b>{fmt(b.startTime)} - {fmt(b.endTime)}</b><p>{b.clientName} · {b.serviceName}</p><p className="text-sm text-gray-500">{b.clientPhone} {b.notes?`· ${b.notes}`:''}</p></div>)}</div><div><h2 className="mb-3 text-xl font-semibold text-[#8a5a42]">Citas de compañeras</h2>{others.map(b=><div key={b.id} className="mb-3 rounded-2xl bg-white p-4 opacity-80 shadow"><b>{fmt(b.startTime)} - {fmt(b.endTime)}</b><p>{b.staffName} · {b.serviceName}</p><p className="text-sm text-gray-500">{b.clientName}</p></div>)}</div></div><div className="mt-8 rounded-3xl bg-white p-5 shadow"><h2 className="text-xl font-semibold text-[#8a5a42]">Resumen económico</h2><table className="mt-4 w-full text-left"><thead><tr><th>Trabajadora</th><th>Citas</th><th>Total</th></tr></thead><tbody>{summary.map(s=><tr key={s.id} className="border-t"><td className="py-2">{s.name}</td><td>{s.totalBookings}</td><td>{Number(s.totalAmount).toFixed(2)} €</td></tr>)}</tbody></table></div></section></main>
}
