import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';

type Customer={id:number;name:string;email?:string|null;phone?:string|null};
type Service={id:number;name:string;price:number;priceLabel?:string|null;totalDuration:number};
type Professional={id:number;name:string;active?:boolean}; type Slot={value:string;label:string};
function today(){return new Date().toISOString().slice(0,10)}
async function getJson(url:string){const r=await fetch(url);const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||'Error cargando datos');return d}

export default function NewStaffBookingPage(){
 const [customers,setCustomers]=useState<Customer[]>([]),[services,setServices]=useState<Service[]>([]),[professionals,setProfessionals]=useState<Professional[]>([]);
 const [customerSearch,setCustomerSearch]=useState(''),[customerId,setCustomerId]=useState(''),[clientName,setClientName]=useState(''),[clientPhone,setClientPhone]=useState(''),[clientEmail,setClientEmail]=useState('');
 const [serviceIds,setServiceIds]=useState<number[]>([]),[professionalId,setProfessionalId]=useState(''),[date,setDate]=useState(today()),[slots,setSlots]=useState<Slot[]>([]),[startTime,setStartTime]=useState(''),[notes,setNotes]=useState('');
 const [loading,setLoading]=useState(true),[loadingSlots,setLoadingSlots]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[created,setCreated]=useState<any>(null);
 useEffect(()=>{Promise.all([getJson('/api/customers'),getJson('/api/services'),getJson('/api/professionals')]).then(([c,s,p])=>{setCustomers(Array.isArray(c)?c:[]);setServices(Array.isArray(s)?s:[]);setProfessionals(Array.isArray(p)?p.filter((x:Professional)=>x.active!==false):[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const filteredCustomers=useMemo(()=>{const q=customerSearch.trim().toLowerCase();return customers.filter(c=>!q||[c.name,c.email||'',c.phone||''].join(' ').toLowerCase().includes(q)).slice(0,25)},[customers,customerSearch]);
 const selectedServices=services.filter(s=>serviceIds.includes(s.id)); const totalPrice=selectedServices.reduce((a,s)=>a+Number(s.price||0),0); const totalDuration=selectedServices.reduce((a,s)=>a+Number(s.totalDuration||0),0);
 useEffect(()=>{setSlots([]);setStartTime('');if(!serviceIds.length||!professionalId||!date)return;setLoadingSlots(true);getJson(`/api/staff/multi-slots?serviceIds=${serviceIds.join(',')}&professionalId=${professionalId}&date=${date}`).then(d=>setSlots(Array.isArray(d)?d.map((v:string)=>({value:v,label:new Date(v).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})})):[])).catch(e=>setError(e.message)).finally(()=>setLoadingSlots(false))},[serviceIds.join(','),professionalId,date]);
 function selectCustomer(c:Customer){setCustomerId(String(c.id));setCustomerSearch(c.name);setClientName(c.name);setClientPhone(c.phone||'');setClientEmail(c.email||'')}
 function toggleService(id:number){setServiceIds(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id])}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!clientName.trim()||!clientPhone.trim())return setError('Nombre y teléfono son obligatorios.');if(!serviceIds.length||!professionalId||!date||!startTime)return setError('Selecciona servicio(s), profesional, fecha y hora.');setSaving(true);try{const r=await fetch('/api/staff/create-booking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId:customerId?Number(customerId):null,name:clientName.trim(),phone:clientPhone.trim(),email:clientEmail.trim()||null,serviceIds,professionalId:Number(professionalId),date,startTime,notes:notes.trim()||null})});const d=await r.json();if(!r.ok)throw new Error(d.error);setCreated(d)}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 if(loading)return <main className="min-h-screen bg-[#f8eee8] p-4"><div className="mx-auto max-w-4xl rounded-3xl bg-white p-6">Cargando...</div></main>;
 if(created)return <main className="min-h-screen bg-[#f8eee8] p-4"><div className="mx-auto max-w-2xl rounded-3xl bg-white p-6 shadow"><div className="rounded-2xl bg-green-100 p-4 font-semibold text-green-800">Cita creada correctamente.</div><h1 className="mt-5 text-3xl font-bold text-[#8a5a42]">Resumen</h1><div className="mt-4 rounded-2xl bg-[#f8eee8] p-5"><p><b>Cliente:</b> {created.clientName}</p><p><b>Servicios:</b> {(created.services||[]).map((s:any)=>s.name).join(' + ')}</p><p><b>Profesional:</b> {created.professional?.name}</p><p><b>Fecha:</b> {new Date(created.startTime).toLocaleString('es-ES')}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link href="/staff/new-booking" className="rounded-xl bg-[#a66f54] px-4 py-3 text-center font-bold text-white">Otra cita</Link><Link href="/staff" className="rounded-xl bg-[#f4e4dc] px-4 py-3 text-center font-bold text-[#8a5a42]">Ver agenda</Link></div></div></main>;
 return <main className="min-h-screen bg-[#f8eee8] p-4 text-[#3b2b25] md:p-8"><div className="mx-auto max-w-5xl"><div className="flex justify-between gap-3"><div><h1 className="text-3xl font-bold text-[#8a5a42]">Nueva cita</h1><p className="text-gray-600">Puedes seleccionar varios servicios.</p></div><Link href="/staff" className="rounded-xl bg-white px-4 py-3 font-bold text-[#8a5a42] shadow">Volver</Link></div>{error&&<div className="mt-4 rounded-xl bg-red-100 p-3 text-red-700">{error}</div>}<form onSubmit={submit} className="mt-6 grid gap-6 lg:grid-cols-2">
 <section className="rounded-3xl bg-white p-5 shadow"><h2 className="text-xl font-bold text-[#8a5a42]">1. Clienta</h2><input value={customerSearch} onChange={e=>{setCustomerSearch(e.target.value);setCustomerId('')}} placeholder="Buscar clienta" className="mt-4 w-full rounded-xl border p-3"/>{customerSearch&&!customerId&&<div className="mt-2 max-h-44 overflow-y-auto rounded-xl border">{filteredCustomers.map(c=><button type="button" key={c.id} onClick={()=>selectCustomer(c)} className="block w-full border-b p-3 text-left"><b>{c.name}</b><span className="block text-xs text-gray-500">{c.phone||''} {c.email||''}</span></button>)}</div>}<div className="mt-4 grid gap-3"><input required value={clientName} onChange={e=>setClientName(e.target.value)} placeholder="Nombre" className="rounded-xl border p-3"/><input required value={clientPhone} onChange={e=>setClientPhone(e.target.value)} placeholder="Teléfono" className="rounded-xl border p-3"/><input type="email" value={clientEmail} onChange={e=>setClientEmail(e.target.value)} placeholder="Email opcional" className="rounded-xl border p-3"/><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Notas" rows={3} className="rounded-xl border p-3"/></div></section>
 <section className="rounded-3xl bg-white p-5 shadow"><h2 className="text-xl font-bold text-[#8a5a42]">2. Servicios y horario</h2><p className="mt-2 text-sm text-gray-500">Pulsa todos los servicios realizados/previstos.</p><div className="mt-4 grid max-h-72 gap-2 overflow-y-auto sm:grid-cols-2">{services.map(s=>{const active=serviceIds.includes(s.id);return <button key={s.id} type="button" onClick={()=>toggleService(s.id)} className={`rounded-xl border p-3 text-left ${active?'border-[#8a5a42] bg-[#f4e4dc] ring-2 ring-[#d8b7a0]':'bg-white'}`}><div className="flex justify-between gap-2"><span className="font-semibold">{s.name}</span>{active&&<span className="font-bold text-green-700">✓</span>}</div><span className="text-sm text-gray-500">{Number(s.price).toFixed(2)} € · {s.totalDuration} min</span></button>})}</div>{serviceIds.length>0&&<div className="mt-4 rounded-xl bg-[#8a5a42] p-4 text-white"><b>{serviceIds.length} servicios</b><span className="float-right font-bold">{totalPrice.toFixed(2)} €</span><p className="text-sm text-white/80">Duración aproximada: {totalDuration} min</p></div>}<div className="mt-4 grid gap-3"><select required value={professionalId} onChange={e=>setProfessionalId(e.target.value)} className="rounded-xl border bg-white p-3"><option value="">Seleccionar profesional</option>{professionals.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)} required className="rounded-xl border p-3"/><select required value={startTime} onChange={e=>setStartTime(e.target.value)} disabled={!serviceIds.length||!professionalId||loadingSlots} className="rounded-xl border bg-white p-3 disabled:bg-gray-100"><option value="">{loadingSlots?'Cargando horarios...':'Seleccionar hora'}</option>{slots.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select><button disabled={saving} className="rounded-xl bg-[#a66f54] px-5 py-4 text-lg font-bold text-white disabled:opacity-50">{saving?'Guardando...':'Crear cita'}</button></div></section>
 </form></div></main>
}
