name: Keep Gema Studio Alive

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Home
        run: curl -I https://gemaestudiodebelleza.es/

      - name: Services
        run: curl -I https://gemaestudiodebelleza.es/api/services

      - name: Settings
        run: curl -I https://gemaestudiodebelleza.es/api/settings

      - name: Slots
        run: curl -I https://gemaestudiodebelleza.es/api/slots
